apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interview-coach.appSecretName" . }}
  labels:
    {{- include "interview-coach.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECURITY_JWT_SECRET: {{ .Values.app.secrets.jwtSecret | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password | quote }}
  SPRING_MAIL_PASSWORD: {{ .Values.app.secrets.springMailPassword | quote }}
