{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "interview-coach.postgresHost" . }}
  labels:
    {{- include "interview-coach.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: postgres
    {{- include "interview-coach.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
{{- end }}
